### PR TITLE
Fix #13 (onLoaded never being called)

### LINKED ISSUE #13: onLoaded never being called
Hi, I am trying to implement this plugin but having issues with getting anything working. I am using the DropzoneView from the example. onCreated is called, but onLoaded is never called and whenever I drag a file into the dropzone it just opens the file in a new tab and onDrop is not called at this point either.

I'm not really sure where to go from here, I get no error output in the flutter console or the javascript web console.

Maybe I am missing something, this is my DropzoneView:

```
    return Container(
      height: 200,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(8.0),
      ),
      child: Stack(
        children: [
          DropzoneView(
            operation: DragOperation.copy,
            cursor: CursorType.grab,
            onCreated: (ctrl) {
              _dropzoneViewController = ctrl;
              print("Controller init");
            },
            onLoaded: () => print('Zone 1 loaded'),
            onError: (ev) => print('Zone 1 error: $ev'),
            onHover: () {
              print('Zone 1 hovered');
            },
            onLeave: () {
              print('Zone 1 left');
            },
            onDrop: (ev) {
              print('Zone 1 drop: ${ev.name}');
            },
          ),
          Center(
            child: Text("Drag and drop"),
          )
        ],
      ),
    );
```

Thanks in advance for any help!

### PR DESCRIPTION
**Pull request by vidklopcic**
With the animationStart event approach I got inconsistent results (I was unable to figure out why). Appending `<script>` tag that dispatches a custom event when the element is attached to DOM, solves all related issues for me (including duplicate firings).

### CODE REVIEW

**Comment by deakjahn** [comment]
Sorry but this is where we come from. :-) The plugin did use this approach until recently but it was changed because, while it works, it gives problems in stricter content security policy environments where inline scripts are frowned upon. See: https://github.com/deakjahn/flutter_dropzone/issues/12

**Comment by vidklopcic** [comment]
Ah, I see :). What about using the MutationObserver?

**Comment by deakjahn** [comment]
Well, I don't know. It was one of the approaches I saw but I was very happy to see this much easier (and "clever" :-) ) trick, and I didn't have your bad experience with it. If nothing else remains, we might need to look into that, too.

**Comment by vidklopcic** [comment]
Yeah, I agree that the current approach is way nicer - it doesn't involve repeatedly querying the DOM on every change. I settled on the solution that removes the listener after the first event.

**Comment by deakjahn** [comment]
I sitll can't understand why you get it twice, though...

**Comment by venkatd** [comment]
@vidklopcic could you share the workaround that you settled on? Is this workaround implemented on the javascript or Flutter layer? I am getting many duplicate onDrop handlers so I also need to find a good workaround.

**Pull request closed without merging**
