### PR TITLE
[WIP] initial version

### PR DESCRIPTION
**Pull request by dxvid-pts**
Work in progress PR migrating `dart:html` to `package:web`

### CODE REVIEW

**Comment by deakjahn** [comment]
OK, the plugin registration could be changed like this:

```
  static void registerWith(Registrar registrar) {
    final self = FlutterDropzonePlugin();
    _isReady = _readyCompleter.future;

    void readyHandler() {
      if (!_readyCompleter.isCompleted) _readyCompleter.complete(true);
    }

    web.window
        .addEventListener('flutter_dropzone_web_ready', readyHandler.toJS);
    FlutterDropzonePlatform.instance = self;
```

**Comment by deakjahn** [comment]
In that case it looks like it can be simply reverted to:

    Future<String> createFileUrl(web.File file) async {
      return web.URL.createObjectURL(file);
    }

    Future<bool> releaseFileUrl(String fileUrl) async {
      web.URL.revokeObjectURL(fileUrl);
      return true;
    }

No need to change `flutter_dropzone.js` at all then. If you undo it, it will be gone from the PR.

**Comment by deakjahn** [comment]
I tried if your repo allows me to upload my new changes and it did (I did it with manual editing, not from the IDE, hence the several separate commits).

**Comment by deakjahn** [comment]
Exception at

https://github.com/dxvid-pts/flutter_dropzone/blob/d96f38436353d215118c700efb60d7b2c0d0c5d0/flutter_dropzone_web/lib/flutter_dropzone_plugin.dart#L42

when trying to run.

**Comment by deakjahn** [comment]
Really? Does it work all right? Which browser did you try it in?

**Comment by deakjahn** [comment]
@dxvid-pts Now I'm not sure whether we should be bold enough to go forward with this...

**Comment by dxvid-pts** [comment]
I'm sorry, I missed your comment! 

In my project I am already using my fork and get no errors. I just tested it on Chrome and Firefox for desktop and on mobile (Android). Can you share the code that leads to this exception? Do you think `package:web` is too immature?

**Comment by deakjahn** [comment]
> Can you share the code that leads to this exception?

Sure. The built-in example in the plugin. :-)

**Comment by dxvid-pts** [comment]
I see... This week is busy but I can work on it next week :-)

**Comment by deakjahn** [comment]
OK, let's return to it then. I checked once more and I still get the error. And I don't really know what could be illegal in the constructor `web.HTMLScriptElement()`, either. :-)

**Comment by dxvid-pts** [comment]
I encountered two bugs when trying out the example. The stack trace was not exactly the same as yours but I think it had the same cause. 

I fixed both so try it out again to check if your exception still happens. Btw da flutter/wasm is now in beta https://medium.com/dartlang/history-of-js-interop-in-dart-98b06991158f

**Comment by deakjahn** [comment]
OK, this is promising but now I get the next error. :-)

```
errors.dart:297 
 Uncaught (in promise) Error: TypeError: Instance of 'LegacyJavaScriptObject': type 'LegacyJavaScriptObject' is not a subtype of type 'Uint8List'
    at Object.throw_ [as throw] (errors.dart:297:3)
    at Object._failedAsCheck (rti.dart:1385:3)
    at dart_rti.Rti.new._generalAsCheckImplementation (rti.dart:1363:3)
    at dart_rti.Rti.new._installSpecializedAsCheck (rti.dart:1258:30)
    at getFileData (flutter_dropzone_web.dart:134:31)
    at getFileData.next (<anonymous>)
    at runBody (async_patch.dart:84:54)
    at Object._async [as async] (async_patch.dart:127:5)
    at flutter_dropzone_web.FlutterDropzoneView.new.getFileData (flutter_dropzone_web.dart:133:32)
```

**Comment by dxvid-pts** [comment]
I got this error as well. Check my latest commit to see how to fix it. Must be a different code line... I'm on vacation now and can't be on my computer in the next few days. I could look at it on Wednesday

**Comment by deakjahn** [comment]
Fair enough, I missed that change. That seems to work all right.

Let's return to it when you can and I'll have to look up again how you're supposed to do a breaking change with a plugin (not the version number part, that's simple, but the branches and tags and whatnot here in GitHub). I already did it once or twice earlier but I have long forgotten... :-)

**Comment by dxvid-pts** [comment]
So it works now? Great! What is left besides versioning and shouldn't it be a minor change based on semver? https://semver.org/

**Comment by deakjahn** [comment]
Well, it was already brought up among the issues that changing the required SDK dependencies should have been done in a breaking change... :-)) Now I'm not really sure whether this version is entirely compatible with all the Flutter environments the current one works in, so it still might be prudent.

**Comment by dxvid-pts** [comment]
Based on my knowledge js_iterop is only available since Dart 3.3 (https://medium.com/dartlang/dart-3-3-325bf2bf6c13) and package:web uses js_iterop internally. So only flutter versions based on Dart 3.3 or older are supported with this change.

**Comment by deakjahn** [comment]
That's not the main question, I already did it twice with this package as well: https://github.com/deakjahn/flutter_dropzone/releases

Simply, I have to check out how it works now in GitHub. I have a TXT with the details that I wrote back then as a note to self but GitHub might have changed something in the meantime. :-)

**Comment by deakjahn** [comment]
Yes, the same issue I always run into and I don't know why. I merge here, everything is OK but I don't get the new version in my IDE (Android Studio). Updating and fetching all say everything is up-to-date, still I have the old version locally. And I always forget when the next time comes how I solved it the last time around. :-))

**Comment by dxvid-pts** [comment]
Nice to see this merged! In case any bug gets issued, feel free to tag me :-)

**Comment by deakjahn** [comment]
You can't avoid that. :-)

**Pull request merged**
